### PR TITLE
Slate example (WIP)

### PR DESCRIPTION
**Pull request by paulgb**
This scaffolds out a Slate example, but changes are not propagated up. It follows [this example](https://docs.slate-yjs.dev/walkthroughs/installation) but I had some difficulty because it seems to be out of sync with the current Slate API.

### CODE REVIEW

**Comment by paulgb** [comment]
/bounty $30 if someone can get this working.

**Comment by zwily** [comment]
I updated your example to work here: https://github.com/drifting-in-space/y-sweet/pull/154

**Comment by paulgb** [comment]
Replaced by #154

**Pull request closed without merging**
